### ISSUE TITLE
hosts example

### ISSUE THREAD

**Issue by lukerussell** [privateip/Ansible-Webinar-Mar2016#1]
Hello,

Would you be able to include an example hosts file with this? For the life of me I can't make it work and I think that's where I'm getting stuck.

I'm personally interested in IOS and NX-OS.

Perhaps you could put this in ansible-examples as well?

**Comment by lukerussell** [comment]
@privateip Could you also include the cli provider?

**Comment by privateip** [comment]
Doh!!
